/* Generated By:JavaCC: Do not edit this line. CCJSqlParserConstants.java */
/*
 * #%L
 * JSQLParser library
 * %%
 * Copyright (C) 2004 - 2013 JSQLParser
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */

package net.sf.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCJSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_AS = 5;
  /** RegularExpression Id. */
  int K_BY = 6;
  /** RegularExpression Id. */
  int K_PARTITIONED = 7;
  /** RegularExpression Id. */
  int K_LOCATION = 8;
  /** RegularExpression Id. */
  int K_STORED = 9;
  /** RegularExpression Id. */
  int K_FORMAT = 10;
  /** RegularExpression Id. */
  int K_DELIMITED = 11;
  /** RegularExpression Id. */
  int K_FIELDS = 12;
  /** RegularExpression Id. */
  int K_TERMINATED = 13;
  /** RegularExpression Id. */
  int K_ESCAPED = 14;
  /** RegularExpression Id. */
  int K_COLLECTION = 15;
  /** RegularExpression Id. */
  int K_ITEMS = 16;
  /** RegularExpression Id. */
  int K_MAP = 17;
  /** RegularExpression Id. */
  int K_KEYS = 18;
  /** RegularExpression Id. */
  int K_LINES = 19;
  /** RegularExpression Id. */
  int K_DEFINED = 20;
  /** RegularExpression Id. */
  int K_SEQUENCEFILE = 21;
  /** RegularExpression Id. */
  int K_TEXTFILE = 22;
  /** RegularExpression Id. */
  int K_RCFILE = 23;
  /** RegularExpression Id. */
  int K_ORC = 24;
  /** RegularExpression Id. */
  int K_PARQUET = 25;
  /** RegularExpression Id. */
  int K_AVRO = 26;
  /** RegularExpression Id. */
  int K_INPUTFORMAT = 27;
  /** RegularExpression Id. */
  int K_DO = 28;
  /** RegularExpression Id. */
  int K_IS = 29;
  /** RegularExpression Id. */
  int K_IN = 30;
  /** RegularExpression Id. */
  int K_OR = 31;
  /** RegularExpression Id. */
  int K_ON = 32;
  /** RegularExpression Id. */
  int K_ALL = 33;
  /** RegularExpression Id. */
  int K_AND = 34;
  /** RegularExpression Id. */
  int K_ANY = 35;
  /** RegularExpression Id. */
  int K_KEY = 36;
  /** RegularExpression Id. */
  int K_NOT = 37;
  /** RegularExpression Id. */
  int K_SET = 38;
  /** RegularExpression Id. */
  int K_ASC = 39;
  /** RegularExpression Id. */
  int K_TOP = 40;
  /** RegularExpression Id. */
  int K_PERCENT = 41;
  /** RegularExpression Id. */
  int K_END = 42;
  /** RegularExpression Id. */
  int K_DESC = 43;
  /** RegularExpression Id. */
  int K_INTO = 44;
  /** RegularExpression Id. */
  int K_NULL = 45;
  /** RegularExpression Id. */
  int K_LIKE = 46;
  /** RegularExpression Id. */
  int K_DROP = 47;
  /** RegularExpression Id. */
  int K_JOIN = 48;
  /** RegularExpression Id. */
  int K_LEFT = 49;
  /** RegularExpression Id. */
  int K_CROSS = 50;
  /** RegularExpression Id. */
  int K_FROM = 51;
  /** RegularExpression Id. */
  int K_OPEN = 52;
  /** RegularExpression Id. */
  int K_CASE = 53;
  /** RegularExpression Id. */
  int K_WHEN = 54;
  /** RegularExpression Id. */
  int K_THEN = 55;
  /** RegularExpression Id. */
  int K_ELSE = 56;
  /** RegularExpression Id. */
  int K_SOME = 57;
  /** RegularExpression Id. */
  int K_FULL = 58;
  /** RegularExpression Id. */
  int K_WITH = 59;
  /** RegularExpression Id. */
  int K_TABLE = 60;
  /** RegularExpression Id. */
  int K_VIEW = 61;
  /** RegularExpression Id. */
  int K_WHERE = 62;
  /** RegularExpression Id. */
  int K_FOR = 63;
  /** RegularExpression Id. */
  int K_PIVOT = 64;
  /** RegularExpression Id. */
  int K_XML = 65;
  /** RegularExpression Id. */
  int K_USING = 66;
  /** RegularExpression Id. */
  int K_UNION = 67;
  /** RegularExpression Id. */
  int K_GROUP = 68;
  /** RegularExpression Id. */
  int K_BEGIN = 69;
  /** RegularExpression Id. */
  int K_INDEX = 70;
  /** RegularExpression Id. */
  int K_INNER = 71;
  /** RegularExpression Id. */
  int K_LIMIT = 72;
  /** RegularExpression Id. */
  int K_OUTER = 73;
  /** RegularExpression Id. */
  int K_ORDER = 74;
  /** RegularExpression Id. */
  int K_RIGHT = 75;
  /** RegularExpression Id. */
  int K_VALUE = 76;
  /** RegularExpression Id. */
  int K_DELETE = 77;
  /** RegularExpression Id. */
  int K_CREATE = 78;
  /** RegularExpression Id. */
  int K_SELECT = 79;
  /** RegularExpression Id. */
  int K_OFFSET = 80;
  /** RegularExpression Id. */
  int K_EXISTS = 81;
  /** RegularExpression Id. */
  int K_HAVING = 82;
  /** RegularExpression Id. */
  int K_INSERT = 83;
  /** RegularExpression Id. */
  int K_UPDATE = 84;
  /** RegularExpression Id. */
  int K_VALUES = 85;
  /** RegularExpression Id. */
  int K_ESCAPE = 86;
  /** RegularExpression Id. */
  int K_PRIMARY = 87;
  /** RegularExpression Id. */
  int K_NATURAL = 88;
  /** RegularExpression Id. */
  int K_REPLACE = 89;
  /** RegularExpression Id. */
  int K_BETWEEN = 90;
  /** RegularExpression Id. */
  int K_TRUNCATE = 91;
  /** RegularExpression Id. */
  int K_DISTINCT = 92;
  /** RegularExpression Id. */
  int K_INTERSECT = 93;
  /** RegularExpression Id. */
  int K_CAST = 94;
  /** RegularExpression Id. */
  int K_EXCEPT = 95;
  /** RegularExpression Id. */
  int K_MINUS = 96;
  /** RegularExpression Id. */
  int K_OVER = 97;
  /** RegularExpression Id. */
  int K_PARTITION = 98;
  /** RegularExpression Id. */
  int K_EXTRACT = 99;
  /** RegularExpression Id. */
  int K_LATERAL = 100;
  /** RegularExpression Id. */
  int K_MATERIALIZED = 101;
  /** RegularExpression Id. */
  int K_INTERVAL = 102;
  /** RegularExpression Id. */
  int K_FOREIGN = 103;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 104;
  /** RegularExpression Id. */
  int K_REFERENCES = 105;
  /** RegularExpression Id. */
  int K_CHARACTER = 106;
  /** RegularExpression Id. */
  int K_VARYING = 107;
  /** RegularExpression Id. */
  int K_START = 108;
  /** RegularExpression Id. */
  int K_CONNECT = 109;
  /** RegularExpression Id. */
  int K_PRIOR = 110;
  /** RegularExpression Id. */
  int K_NOCYCLE = 111;
  /** RegularExpression Id. */
  int K_SIBLINGS = 112;
  /** RegularExpression Id. */
  int K_ALTER = 113;
  /** RegularExpression Id. */
  int K_ADD = 114;
  /** RegularExpression Id. */
  int K_COLUMN = 115;
  /** RegularExpression Id. */
  int K_NULLS = 116;
  /** RegularExpression Id. */
  int K_FIRST = 117;
  /** RegularExpression Id. */
  int K_LAST = 118;
  /** RegularExpression Id. */
  int K_ROWS = 119;
  /** RegularExpression Id. */
  int K_RANGE = 120;
  /** RegularExpression Id. */
  int K_UNBOUNDED = 121;
  /** RegularExpression Id. */
  int K_PRECEDING = 122;
  /** RegularExpression Id. */
  int K_FOLLOWING = 123;
  /** RegularExpression Id. */
  int K_CURRENT = 124;
  /** RegularExpression Id. */
  int K_ROW = 125;
  /** RegularExpression Id. */
  int K_TO = 126;
  /** RegularExpression Id. */
  int K_SHOW = 127;
  /** RegularExpression Id. */
  int S_DOUBLE = 128;
  /** RegularExpression Id. */
  int S_LONG = 129;
  /** RegularExpression Id. */
  int DIGIT = 130;
  /** RegularExpression Id. */
  int LINE_COMMENT = 131;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 132;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 133;
  /** RegularExpression Id. */
  int LETTER = 134;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 135;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 136;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 137;
  /** RegularExpression Id. */
  int ADDITIONAL_LETTERS = 138;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AS\"",
    "\"BY\"",
    "\"PARTITIONED\"",
    "\"LOCATION\"",
    "\"STORED\"",
    "\"FORMAT\"",
    "\"DELIMITED\"",
    "\"FIELDS\"",
    "\"TERMINATED\"",
    "\"ESCAPED\"",
    "\"COLLECTION\"",
    "\"ITEMS\"",
    "\"MAP\"",
    "\"KEYS\"",
    "\"LINES\"",
    "\"DEFINED\"",
    "\"SEQUENCEFILE\"",
    "\"TEXTFILE\"",
    "\"RCFILE\"",
    "\"ORC\"",
    "\"PARQUET\"",
    "\"AVRO\"",
    "\"INPUTFORMAT\"",
    "\"DO\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"KEY\"",
    "\"NOT\"",
    "\"SET\"",
    "\"ASC\"",
    "\"TOP\"",
    "\"PERCENT\"",
    "\"END\"",
    "\"DESC\"",
    "\"INTO\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"DROP\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"CROSS\"",
    "\"FROM\"",
    "\"OPEN\"",
    "\"CASE\"",
    "\"WHEN\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"SOME\"",
    "\"FULL\"",
    "\"WITH\"",
    "\"TABLE\"",
    "\"VIEW\"",
    "\"WHERE\"",
    "\"FOR\"",
    "\"PIVOT\"",
    "\"XML\"",
    "\"USING\"",
    "\"UNION\"",
    "\"GROUP\"",
    "\"BEGIN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"OUTER\"",
    "\"ORDER\"",
    "\"RIGHT\"",
    "\"VALUE\"",
    "\"DELETE\"",
    "\"CREATE\"",
    "\"SELECT\"",
    "\"OFFSET\"",
    "\"EXISTS\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"ESCAPE\"",
    "\"PRIMARY\"",
    "\"NATURAL\"",
    "\"REPLACE\"",
    "\"BETWEEN\"",
    "\"TRUNCATE\"",
    "\"DISTINCT\"",
    "\"INTERSECT\"",
    "\"CAST\"",
    "\"EXCEPT\"",
    "\"MINUS\"",
    "\"OVER\"",
    "\"PARTITION\"",
    "\"EXTRACT\"",
    "\"LATERAL\"",
    "\"MATERIALIZED\"",
    "\"INTERVAL\"",
    "\"FOREIGN\"",
    "\"CONSTRAINT\"",
    "\"REFERENCES\"",
    "\"CHARACTER\"",
    "\"VARYING\"",
    "\"START\"",
    "\"CONNECT\"",
    "\"PRIOR\"",
    "\"NOCYCLE\"",
    "\"SIBLINGS\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\"COLUMN\"",
    "\"NULLS\"",
    "\"FIRST\"",
    "\"LAST\"",
    "\"ROWS\"",
    "\"RANGE\"",
    "\"UNBOUNDED\"",
    "\"PRECEDING\"",
    "\"FOLLOWING\"",
    "\"CURRENT\"",
    "\"ROW\"",
    "\"TO\"",
    "\"SHOW\"",
    "<S_DOUBLE>",
    "<S_LONG>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<ADDITIONAL_LETTERS>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"*\"",
    "\"?\"",
    "\"(+)\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"@@\"",
    "\"~\"",
    "\"~*\"",
    "\"!~\"",
    "\"!~*\"",
    "\"||\"",
    "\"|\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"::\"",
    "\":\"",
    "\"{fn\"",
  };

}
