/* Generated By:JavaCC: Do not edit this line. ClusterURIParserConstants.java */
package com.asksunny.sql.uri;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ClusterURIParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_HTTP = 1;
  /** RegularExpression Id. */
  int K_HTTPS = 2;
  /** RegularExpression Id. */
  int K_FTP = 3;
  /** RegularExpression Id. */
  int K_FTPS = 4;
  /** RegularExpression Id. */
  int K_HDFS = 5;
  /** RegularExpression Id. */
  int K_JDBC = 6;
  /** RegularExpression Id. */
  int K_WEBHDFS = 7;
  /** RegularExpression Id. */
  int K_FILE = 8;
  /** RegularExpression Id. */
  int K_SMTP = 9;
  /** RegularExpression Id. */
  int K_SCP = 10;
  /** RegularExpression Id. */
  int K_SFTP = 11;
  /** RegularExpression Id. */
  int S_DOMAINNAME = 12;
  /** RegularExpression Id. */
  int S_URLSAFE_WORD = 13;
  /** RegularExpression Id. */
  int S_PORTNUM = 14;
  /** RegularExpression Id. */
  int S_SPEARATOR = 15;
  /** RegularExpression Id. */
  int URLENCODE_CHAR = 16;
  /** RegularExpression Id. */
  int CHARS = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"HTTP\"",
    "\"HTTPS\"",
    "\"FTP\"",
    "\"FTPS\"",
    "\"HDFS\"",
    "\"JDBC\"",
    "\"WEBHDFS\"",
    "\"FILE\"",
    "\"SMTP\"",
    "\"SCP\"",
    "\"SFTP\"",
    "<S_DOMAINNAME>",
    "<S_URLSAFE_WORD>",
    "<S_PORTNUM>",
    "\":\"",
    "<URLENCODE_CHAR>",
    "<CHARS>",
    "\"/\"",
    "\"//\"",
    "\",\"",
    "\";\"",
    "\"?\"",
    "\"&\"",
    "\"+\"",
    "\"=\"",
    "\"@\"",
    "\".\"",
  };

}
